# Generated by Django 5.2.6 on 2025-09-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.CharField()),
                ('cart_price', models.IntegerField()),
                ('expiry_date', models.IntegerField()),
                ('ratings', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
